stages:
  - install
  - build
  - deploy

variables:
#  NODE_ENV: production
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR'
  OUTPUT_PATH: '$CI_PROJECT_DIR/dist'
  APP_BUILD_COMMAND: |
    ls . && \
    echo "Generating .env file with CI/CD environment variables..." && \
    echo "VITE_KC_URL=$KC_URL" > .env && \
    echo "VITE_KC_REALM=$KC_REALM" >> .env && \
    echo "VITE_KC_CLIENT_ID=$KC_CLIENT_ID" >> .env && \
    echo "VITE_API_URL=$API_URL" >> .env && \
    npm run build

before_script:
  - echo "Starting pipeline..."

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:20
  variables:
    NPM_CONFIG_PRODUCTION: "false"   # ensure dev deps are installed
  script:
    - npm ci --include=dev
  artifacts:
    paths:
      - node_modules/

build_project:
  stage: build
  image: node:20
  script:
    - echo "Keycloak URL $KC_URL"
    - echo "API_URL $API_URL"
    - echo "VITE_KC_URL=$KC_URL" > .env
    - echo "VITE_KC_REALM=$KC_REALM" >> .env
    - echo "VITE_KC_CLIENT_ID=$KC_CLIENT_ID" >> .env
    - echo "VITE_API_URL=$API_URL" >> .env
    - cat .env
    - npm run build
  artifacts:
    paths:
      - dist/



deploy:
  stage: deploy
  dependencies: [build_project]
  image: mcr.microsoft.com/azure-cli
  script:
    - az storage blob upload-batch --account-name "$AZURE_STORAGE_ACCOUNT" --account-key "$AZURE_STORAGE_KEY" -s dist -d '$web' --overwrite
  only:
    - main
    - resit


